language: generic
sudo: false

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack
  - $HOME/.cache
  - $HOME/boot
  - $HOME/ghcjs
  - $HOME/.ghcjs
  - $HOME/../ghcjs-th
  - $HOME/packages/web/.ghc
  - $HOME/packages/web/.cabal
  - $HOME/packages/web/.stack
  - $HOME/packages/web/.cache
  - $HOME/packages/web/boot
  - $HOME/packages/web/ghcjs
  - $HOME/packages/web/.ghcjs
  - $HOME/packages/web/ghcjs-th
  - $HOME/packages/ghcjs-th
  - $HOME/../ghcjs-th
  - $TRAVIS_BUILD_DIR/.stack-work

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - export PATH=/opt/ghc/7.10.2/bin:$PATH
  - sudo apt-get install curl
  - stack upgrade --allow-different-user --binary-version 2.1.1
  - stack install --only-dependencies --allow-different-user
  - stack install shake --allow-different-user

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - ghc-7.10.2

script:
  - stack exec --allow-different-user -- shake
  
after_script:
  - travis_retry curl -L https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.4.0/shc-linux-x64-8.0.1.tar.bz2 | tar -xj
  - ./shc ocamlhs ocamlhs-test
