name:                ocamlhs
version:             0.1.0.0
github:              "githubuser/ocamlhs"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ocamlhs#readme>

build-type: Custom

dependencies:
- base >= 4.7 && < 5
- BNFC >= 2.8.1 && <= 2.8.2
- array >= 0.5.3.0
- containers >= 0.6.0.1
- mtl >= 2.2.0.1
- optparse-applicative >= 0.14.0.0
- raw-strings-qq >= 1.1
- para >= 1.0

library:
  source-dirs:
  - src
  - parser

executables:
  interpreter:
    main:                Main.hs
    source-dirs:
    - app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ocamlhs

tests:
  ocamlhs-test:
    main:                Main.hs
    source-dirs:
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    defaults: hspec/hspec@master
    dependencies:
    - ocamlhs
