name:                ocamlhs
version:             0.1.0.0
github:              "styczynski/ocaml.hs"
license:             MIT
author:              "Piotr Styczyński"
maintainer:          "piotr@styczynski.in"
copyright:           "2019 Piotr Styczyński"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Interpreter for Ocaml language subset
category:            Interpreter

description:         Please see the README on GitHub at <https://github.com/styczynski/ocaml.hs#readme>

build-type: Custom

dependencies:
- base >= 4.7 && < 5
- BNFC >= 2.8.1 && <= 2.8.2
- array >= 0.5.3.0
- containers >= 0.5.7.1
- mtl >= 2.2.0.1
- optparse-applicative >= 0.14.0.0
- raw-strings-qq >= 1.1
- para >= 1.0
- text >= 1.2.3.1
- split >= 0.2.3.3
- butcher >= 1.3.1
- multistate >= 0.7.1.1
- brittany >= 0.12.0.0
- deque >= 0.4.2.3
- strict-list >= 0.1.4
- QuickCheck >= 2.12.6.1

library:
  source-dirs:
  - src
  - parser

executables:
  interpreter:
    main:                Main.hs
    source-dirs:
    - app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ocamlhs

tests:
  ocamlhs-test:
    main:                Main.hs
    source-dirs:
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    defaults: hspec/hspec@master
    dependencies:
    - ocamlhs
    - regex-tdfa >= 1.2.3.2
